[tool.poetry]
name = "8puzzle"
version = "0.1.0"
description = ""
authors = ["Abhijeet <abhijeetpoudel@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
graphviz = "^0.20.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
